name: Updating File In Another Repo
on:
  push:
    branches:
      - main
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 14
    
      - name: Update text File
        run: |
              git clone https://github.com/saurabhwohlig/Repo2.git
              cd Repo2
              git checkout main
              commit_count=$(($(grep -oP 'my commit count is : \K\d+' data.txt) + 50))
              sed -i "s/my commit count is : [0-9]\+/my commit count is : $commit_count/" data.txt
              cat data.txt
              echo "my commit count is"
              git config --global user.email "saurabh.mishra@wohlig.com"
              git config --global user.name "saurabhwohlig"
              git status
              git remote -v
              git add .
              git commit -m "updating newer data"
              git remote set-url origin https://${{ secrets.ACCESSTOKEN_GITHUB }}@github.com/saurabhwohlig/Repo2.git
              git push origin main                   